wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.17.9
    framework: huggingface
    huggingface_version: 4.34.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1725698099
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.17.9
      6: 4.34.0
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
